// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {history} from '../models';
import {csync} from '../models';
import {permission} from '../models';

export function AttachFile(arg1:string):Promise<void>;

export function DetachFile(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<api.UIState>;

export function Files():Promise<history.Service>;

export function Greet(arg1:string):Promise<string>;

export function ListCommands():Promise<Array<api.CommandInfo>>;

export function ListDirectory(arg1:string):Promise<Array<api.FileInfo>>;

export function LspClients():Promise<csync.Map_string_github_com_upperxcode_jx2ai_agent_api_internal_lsp_Client_>;

export function Permissions():Promise<permission.Service>;

export function ReadFile(arg1:string):Promise<string>;

export function SetCurrentFile(arg1:string):Promise<void>;
