// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachFile(arg1) {
  return window['go']['api']['App']['AttachFile'](arg1);
}

export function DetachFile(arg1) {
  return window['go']['api']['App']['DetachFile'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['api']['App']['ExecuteCommand'](arg1);
}

export function Greet(arg1) {
  return window['go']['api']['App']['Greet'](arg1);
}

export function ListCommands() {
  return window['go']['api']['App']['ListCommands']();
}

export function ListDirectory(arg1) {
  return window['go']['api']['App']['ListDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['api']['App']['ReadFile'](arg1);
}
