// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AttachFile(arg1:string):Promise<void>;

export function DetachFile(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<api.UIState>;

export function Greet(arg1:string):Promise<string>;

export function ListCommands():Promise<Array<api.CommandInfo>>;

export function ListDirectory(arg1:string):Promise<Array<api.FileInfo>>;

export function ReadFile(arg1:string):Promise<string>;
